CREATE DATABASE awae;
USE awae;

CREATE TABLE Usuário(
idUsuário INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(40),
email VARCHAR(40),
senha VARCHAR(40)
);

CREATE TABLE Quiz(
idQuiz INT PRIMARY KEY AUTO_INCREMENT,
tentativa INT,
FkUsuário INT, CONSTRAINT ctfkUsuário 
			   FOREIGN KEY (FkUsuário) REFERENCES Usuário(idUsuário)
)AUTO_INCREMENT = 50;

CREATE TABLE Nota(
idNota INT PRIMARY KEY AUTO_INCREMENT,
Nome varchar (45),
Nota INT,
FkQuiz INT, CONSTRAINT ctfkQuiz
			FOREIGN KEY (FkQuiz) REFERENCES Quiz(idQuiz)
)AUTO_INCREMENT = 100;

select * from Usuário;